# Numpy class

In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [5]:
type(np.array([[2,3,4],[4,5,6]]))

numpy.ndarray

In [6]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [7]:
l=[[1,2,3,4],[2,3,4,5]]

In [8]:
l[0][0]

1

In [9]:
a=np.array([3,4,5,6],ndmin=5)

In [10]:
a

array([[[[[3, 4, 5, 6]]]]])

In [11]:
a=np.array([3,4,5,6],ndmin=3)

In [12]:
a

array([[[3, 4, 5, 6]]])

In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.ndim

2

In [17]:
np.random.randint(1,10,(4,4))

array([[3, 6, 9, 4],
       [6, 4, 4, 6],
       [2, 3, 2, 9],
       [6, 6, 4, 6]])

In [19]:
np.random.randint(1,10,(4,4,2))

array([[[4, 3],
        [8, 8],
        [6, 9],
        [6, 9]],

       [[5, 8],
        [4, 6],
        [6, 4],
        [9, 2]],

       [[9, 2],
        [7, 4],
        [3, 7],
        [2, 6]],

       [[3, 4],
        [1, 3],
        [2, 3],
        [1, 8]]])

In [20]:
import numpy as np

In [21]:
l=[1,2,3,4,5,6]

In [22]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [23]:
l1=[4,5,6,7,'sudh',34.565,True]

In [28]:
a1=np.array(l1)

In [29]:
a2=np.array([[1,2,3],[4,5,6]])

In [30]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [31]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [32]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [34]:
a1.ndim

1

In [35]:
a2.ndim

2

In [36]:
a3.ndim

3

In [37]:
a1.size

7

In [38]:
a2.size

6

In [39]:
a3.size

9

In [41]:
a1.shape

(7,)

In [42]:
a2.shape

(2, 3)

In [43]:
a3.shape

(1, 3, 3)

In [44]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [46]:
np.random.randint(2,50)

39

In [47]:
np.random.randint(2,50,(3,4))

array([[25, 37, 26, 36],
       [ 7, 11, 41,  8],
       [47, 49, 28,  4]])

In [48]:
np.random.randint(2,50,(2,3,4))

array([[[28, 31, 46,  9],
        [43, 39, 20, 39],
        [35,  9,  6, 36]],

       [[39, 15, 39,  2],
        [19, 36, 19, 19],
        [40, 30, 14,  9]]])

In [49]:
np.random.rand(4,4)

array([[0.22276448, 0.13737769, 0.57865557, 0.70130283],
       [0.56924467, 0.44814005, 0.59749503, 0.84207863],
       [0.66002947, 0.09010742, 0.26316509, 0.55189196],
       [0.3925224 , 0.43270686, 0.1473136 , 0.43611977]])

In [50]:
np.random.randn(4,4)

array([[-0.46196276, -0.04960863, -1.62865098,  1.8924814 ],
       [-0.83944739, -1.27389348, -1.48118013, -0.77652666],
       [ 0.56297121,  0.47006412,  1.1750289 ,  0.7563418 ],
       [-0.77451278,  0.095679  ,  0.10121087,  0.10954559]])

In [51]:
a4=np.random.randn(4,4)

In [52]:
a4.reshape(2,8)

array([[ 1.08803062,  1.19106915,  0.75970724,  0.43294299,  1.30771189,
        -0.42027282, -0.39920515, -0.2222933 ],
       [ 0.38401855,  1.7865552 , -1.2058812 ,  0.41400098,  0.19621577,
         0.65778194, -1.45739621,  0.77892967]])

In [53]:
a4.reshape(8,2)

array([[ 1.08803062,  1.19106915],
       [ 0.75970724,  0.43294299],
       [ 1.30771189, -0.42027282],
       [-0.39920515, -0.2222933 ],
       [ 0.38401855,  1.7865552 ],
       [-1.2058812 ,  0.41400098],
       [ 0.19621577,  0.65778194],
       [-1.45739621,  0.77892967]])

In [54]:
a4.reshape(16,1)

array([[ 1.08803062],
       [ 1.19106915],
       [ 0.75970724],
       [ 0.43294299],
       [ 1.30771189],
       [-0.42027282],
       [-0.39920515],
       [-0.2222933 ],
       [ 0.38401855],
       [ 1.7865552 ],
       [-1.2058812 ],
       [ 0.41400098],
       [ 0.19621577],
       [ 0.65778194],
       [-1.45739621],
       [ 0.77892967]])

In [55]:
a4.reshape(2,-1)

array([[ 1.08803062,  1.19106915,  0.75970724,  0.43294299,  1.30771189,
        -0.42027282, -0.39920515, -0.2222933 ],
       [ 0.38401855,  1.7865552 , -1.2058812 ,  0.41400098,  0.19621577,
         0.65778194, -1.45739621,  0.77892967]])

In [56]:
a4.reshape(2,-4)

array([[ 1.08803062,  1.19106915,  0.75970724,  0.43294299,  1.30771189,
        -0.42027282, -0.39920515, -0.2222933 ],
       [ 0.38401855,  1.7865552 , -1.2058812 ,  0.41400098,  0.19621577,
         0.65778194, -1.45739621,  0.77892967]])

In [57]:
a4.reshape(2,2,4)

array([[[ 1.08803062,  1.19106915,  0.75970724,  0.43294299],
        [ 1.30771189, -0.42027282, -0.39920515, -0.2222933 ]],

       [[ 0.38401855,  1.7865552 , -1.2058812 ,  0.41400098],
        [ 0.19621577,  0.65778194, -1.45739621,  0.77892967]]])

In [58]:
a4.reshape(1,1,1,1,1,2,2,4)

array([[[[[[[[ 1.08803062,  1.19106915,  0.75970724,  0.43294299],
             [ 1.30771189, -0.42027282, -0.39920515, -0.2222933 ]],

            [[ 0.38401855,  1.7865552 , -1.2058812 ,  0.41400098],
             [ 0.19621577,  0.65778194, -1.45739621,  0.77892967]]]]]]]])

In [59]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [60]:
a1[0]

'4'

In [61]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [62]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [63]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [64]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [65]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a2[0]

array([1, 2, 3])

In [69]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [70]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [71]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [72]:
a5=np.random.randint(2,90,(6,5))

In [73]:
a5

array([[17, 47, 49, 74, 15],
       [43, 71, 30, 70, 44],
       [ 8, 76, 58, 57,  5],
       [64, 84, 47, 22, 21],
       [87, 51, 29, 60,  9],
       [57, 23, 17, 57, 39]])

In [74]:
a5[a5>40]

array([47, 49, 74, 43, 71, 70, 44, 76, 58, 57, 64, 84, 47, 87, 51, 60, 57,
       57])

In [75]:
a5

array([[17, 47, 49, 74, 15],
       [43, 71, 30, 70, 44],
       [ 8, 76, 58, 57,  5],
       [64, 84, 47, 22, 21],
       [87, 51, 29, 60,  9],
       [57, 23, 17, 57, 39]])

In [77]:
a5[0,1]=100

In [78]:
a5

array([[ 17, 100,  49,  74,  15],
       [ 43,  71,  30,  70,  44],
       [  8,  76,  58,  57,   5],
       [ 64,  84,  47,  22,  21],
       [ 87,  51,  29,  60,   9],
       [ 57,  23,  17,  57,  39]])

In [83]:
a6=np.random.randint(0,3,(3,3))

In [80]:
a7=np.random.randint(0,3,(3,3))

In [84]:
a6

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]])

In [82]:
a7

array([[1, 0, 1],
       [2, 1, 2],
       [0, 0, 2]])

In [85]:
a6*a7

array([[0, 0, 2],
       [0, 1, 4],
       [0, 0, 4]])

In [86]:
a6@a7

array([[2, 1, 6],
       [2, 1, 6],
       [1, 0, 5]])

In [87]:
a6@a7

array([[2, 1, 6],
       [2, 1, 6],
       [1, 0, 5]])

In [88]:
a6+100

array([[100, 101, 102],
       [100, 101, 102],
       [101, 100, 102]])

In [89]:
a6*2

array([[0, 2, 4],
       [0, 2, 4],
       [2, 0, 4]])

In [90]:
a6/0

C:\Users\dell\AppData\Local\Temp\ipykernel_33752\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\dell\AppData\Local\Temp\ipykernel_33752\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, inf, inf],
       [nan, inf, inf],
       [inf, nan, inf]])

In [91]:
a6

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]])

In [92]:
a6**3

array([[0, 1, 8],
       [0, 1, 8],
       [1, 0, 8]], dtype=int32)

In [95]:
a8=np.zeros((4,4))

In [96]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
a9=np.ones((4,5))

In [99]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [102]:
a9+np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [103]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
a9+np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [105]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [107]:
np.array([[1,2,3,4]]).T+a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [108]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [109]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [110]:
a6.T

array([[0, 0, 1],
       [1, 1, 0],
       [2, 2, 2]])

In [111]:
a6

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]])

In [112]:
a5

array([[ 17, 100,  49,  74,  15],
       [ 43,  71,  30,  70,  44],
       [  8,  76,  58,  57,   5],
       [ 64,  84,  47,  22,  21],
       [ 87,  51,  29,  60,   9],
       [ 57,  23,  17,  57,  39]])

In [113]:
np.sqrt(a5)

array([[ 4.12310563, 10.        ,  7.        ,  8.60232527,  3.87298335],
       [ 6.55743852,  8.42614977,  5.47722558,  8.36660027,  6.63324958],
       [ 2.82842712,  8.71779789,  7.61577311,  7.54983444,  2.23606798],
       [ 8.        ,  9.16515139,  6.8556546 ,  4.69041576,  4.58257569],
       [ 9.32737905,  7.14142843,  5.38516481,  7.74596669,  3.        ],
       [ 7.54983444,  4.79583152,  4.12310563,  7.54983444,  6.244998  ]])

In [114]:
np.log10(a5)

array([[1.23044892, 2.        , 1.69019608, 1.86923172, 1.17609126],
       [1.63346846, 1.85125835, 1.47712125, 1.84509804, 1.64345268],
       [0.90308999, 1.88081359, 1.76342799, 1.75587486, 0.69897   ],
       [1.80617997, 1.92427929, 1.67209786, 1.34242268, 1.32221929],
       [1.93951925, 1.70757018, 1.462398  , 1.77815125, 0.95424251],
       [1.75587486, 1.36172784, 1.23044892, 1.75587486, 1.59106461]])

In [115]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [117]:
np.arange(0,10,2.5)

array([0. , 2.5, 5. , 7.5])

In [118]:
np.arange(1.8,10.7,2.8)

array([ 1.8,  4.6,  7.4, 10.2])

In [119]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [120]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [121]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])